basic cli arguments
subalterngames/cacophony pull request #5
Opened 2023-10-27 19:22 UTC by tversteeg

Currently includes `[FILE]`, `--help`, `--version` & `--data-dir`.

I've made paths global with a `OnceLock`. This is more efficient in that it doesn't need to setup and load all the paths multiple times, and was also required for persisting the paths across the whole session.

I would like to do something similar with the config ini which also seems to be loaded at multiple places, so I can expose changing things such as the window sizes. Is that ok with you?

2023-10-29 14:03 UTC, subalterngames requested changes

2023-10-29 14:03 UTC, subalterngames commented on io/src/save.rs
> +pub struct Save {
This should be reverted. Ideally, main.rs parses the cli args and then calls a function in io which loads the save file. I don't want to expose the save file to the other crates.

2023-10-29 14:07 UTC, subalterngames commented
@tversteeg 

> I've got some issues with running the actual program, so I couldn't properly test the file loading in the way I wanted. I'll open some issues for that but I would highly recommend testing my fork yourself before merging.

Thanks for the warning. Can you tell me specifically what doesn't work?

2023-10-29 16:47 UTC, tversteeg commented
> Thanks for the warning. Can you tell me specifically what doesn't work?

Whenever I press any of the F keys I get a super fast flashing red text but it's too fast for me to read. I'll open a issue tomorrow when I get home. It's not related to any of my changes because I also get it on the main branch.

2023-10-30 20:50 UTC, subalterngames commented
Thanks for the revisions. Could you fix the clippy warnings?

2023-10-31 20:06 UTC, tversteeg commented
Fixed the clippy warnings.

2023-11-01 13:03 UTC, subalterngames approved these changes

2023-11-01 13:04 UTC, merged